<?php //[STAMP] a6e9b191d980221f283cba44a4ae1415
namespace _generated;

    // This class was automatically generated by build task
    // You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Scenario;
use Helper\Functional;

trait FunctionalTesterActions
{
    /**
     * @return Scenario
     */
    abstract protected function getScenario();


}
